<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>Utilme.SdpTransform</AssemblyName>
		<RootNamespace>UtilmeSdpTransform</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>melihercan</Authors>
		<Description>SDP parser and writer for .NET.
It transforms between SDP text, object, and JSON representations.</Description>
		<Copyright>melihercan 2022</Copyright>
		<PackageProjectUrl>https://github.com/melihercan/Utilme</PackageProjectUrl>
		<PackageIcon>me.png</PackageIcon>
		<RepositoryUrl>https://github.com/melihercan/Utilme/tree/master/SdpTransform</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>.NET SDP Transform Text Object JSON</PackageTags>
		<PackageReleaseNotes>Creation</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\doc\me.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>


</Project>
